version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

